# Generated by Django 5.2.1 on 2025-05-16 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PAN', 'PAN Card'), ('AADHAAR', 'Aadhaar Card'), ('BANK', 'Bank Details / Passbook'), ('FORM16A', 'Form 16A'), ('INVOICE', 'Sales Invoices / Register'), ('PL', 'Profit & Loss Statement'), ('BS', 'Balance Sheet'), ('SALARY', 'Salary Slip'), ('FORM16B', 'Form 16B'), ('RENT', 'Rent Agreement'), ('CAPITAL_GAIN', 'Capital Gain Details')], max_length=50)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
