# Generated by Django 5.2.1 on 2025-05-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_returnfiling_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnfiling',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
