# Generated by Django 5.2.1 on 2025-05-16 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_delete_returnfiling'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiledReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_type', models.CharField(choices=[('GSTR-1', 'GSTR-1'), ('GSTR-3B', 'GSTR-3B'), ('IT', 'Income Tax')], max_length=10)),
                ('due_date', models.DateField()),
                ('filed_date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('filed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_by_ca', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('client', 'return_type', 'due_date')},
            },
        ),
    ]
