# Generated by Django 5.2.1 on 2025-05-20 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tds_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TDSRecord',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
